FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

SRC_URI:append = " file://system-user.dtsi"

# Standalone capture-pipeline overlay. EXTRA_DT_FILES copies it into
# DT_FILES_PATH and adds it to SRC_URI; the recipe sees its top-line /plugin/;
# and compiles it (with dtc -@) into camera-overlay.dtbo. It /include/s the
# autogenerated pl.dtsi (resolved via the plnx_workspace include dir), so all PL
# labels bind at compile time. NOTE: this is EXTRA_DT_FILES, not EXTRA_OVERLAYS
# — EXTRA_OVERLAYS would also #include it into the (non-plugin) base system-top.dts.
EXTRA_DT_FILES:append = " camera-overlay.dts"

require ${@'device-tree-sdt.inc' if d.getVar('SYSTEM_DTFILE') != '' else ''}
