`timescale 1ns/1ps
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module blob_detect_rle_regs (
        input wire clk,
        input wire rst_n,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [5:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [31:0] s_axil_wdata,
        input wire [3:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [5:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [31:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        input blob_detect_rle_regs_pkg::blob_detect_rle_regs__in_t hwif_in,
        output blob_detect_rle_regs_pkg::blob_detect_rle_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [5:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [5:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[5:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[5:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[5:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    logic axil_resp_buffer_is_wr[2];
    logic axil_resp_buffer_err[2];
    logic [31:0] axil_resp_buffer_rdata[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk) begin
        if(~rst_n) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer_is_wr[i] <= '0;
                axil_resp_buffer_err[i] <= '0;
                axil_resp_buffer_rdata[i] <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '0;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_rd_err;
                    axil_resp_buffer_rdata[axil_resp_wptr[0:0]] <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '1;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer_is_wr[axil_resp_rptr[0:0]]) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer_rdata[axil_resp_rptr[0:0]];
        if(axil_resp_buffer_err[axil_resp_rptr[0:0]]) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic CTRL;
        logic STATUS;
        logic HRES;
        logic VRES;
        logic BLOB_ADDR;
        logic BLOB_COUNT_RD;
        logic BLOB_SX;
        logic BLOB_SY;
        logic BLOB_XMIN;
        logic BLOB_XMAX;
        logic BLOB_YMIN;
        logic BLOB_YMAX;
        logic FRAME_CNT;
        logic MAX_BLOBS_CFG;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [5:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.CTRL = cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.STATUS = cpuif_req_masked & (cpuif_addr == 6'h4) & !cpuif_req_is_wr;
        decoded_reg_strb.HRES = cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.VRES = cpuif_req_masked & (cpuif_addr == 6'hc);
        decoded_reg_strb.BLOB_ADDR = cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.BLOB_COUNT_RD = cpuif_req_masked & (cpuif_addr == 6'h14) & !cpuif_req_is_wr;
        decoded_reg_strb.BLOB_SX = cpuif_req_masked & (cpuif_addr == 6'h18) & !cpuif_req_is_wr;
        decoded_reg_strb.BLOB_SY = cpuif_req_masked & (cpuif_addr == 6'h1c) & !cpuif_req_is_wr;
        decoded_reg_strb.BLOB_XMIN = cpuif_req_masked & (cpuif_addr == 6'h20) & !cpuif_req_is_wr;
        decoded_reg_strb.BLOB_XMAX = cpuif_req_masked & (cpuif_addr == 6'h24) & !cpuif_req_is_wr;
        decoded_reg_strb.BLOB_YMIN = cpuif_req_masked & (cpuif_addr == 6'h28) & !cpuif_req_is_wr;
        decoded_reg_strb.BLOB_YMAX = cpuif_req_masked & (cpuif_addr == 6'h2c) & !cpuif_req_is_wr;
        decoded_reg_strb.FRAME_CNT = cpuif_req_masked & (cpuif_addr == 6'h30) & !cpuif_req_is_wr;
        decoded_reg_strb.MAX_BLOBS_CFG = cpuif_req_masked & (cpuif_addr == 6'h34) & !cpuif_req_is_wr;
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } RESET;
            struct {
                logic next;
                logic load_next;
            } START;
            struct {
                logic next;
                logic load_next;
            } IRQ_CLEAR;
            struct {
                logic next;
                logic load_next;
            } BLOB_ADDR_AUTOINC;
            struct {
                logic [7:0] next;
                logic load_next;
            } THRESHOLD;
        } CTRL;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } HRES;
        } HRES;
        struct {
            struct {
                logic [15:0] next;
                logic load_next;
            } VRES;
        } VRES;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } BLOB_ADDR;
        } BLOB_ADDR;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } RESET;
            struct {
                logic value;
            } START;
            struct {
                logic value;
            } IRQ_CLEAR;
            struct {
                logic value;
            } BLOB_ADDR_AUTOINC;
            struct {
                logic [7:0] value;
            } THRESHOLD;
        } CTRL;
        struct {
            struct {
                logic [15:0] value;
            } HRES;
        } HRES;
        struct {
            struct {
                logic [15:0] value;
            } VRES;
        } VRES;
        struct {
            struct {
                logic [7:0] value;
            } BLOB_ADDR;
        } BLOB_ADDR;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: blob_detect_rle_regs.CTRL.RESET
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.RESET.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.RESET.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.CTRL.RESET.next = next_c;
        field_combo.CTRL.RESET.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.CTRL.RESET.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.RESET.load_next) begin
                field_storage.CTRL.RESET.value <= field_combo.CTRL.RESET.next;
            end
        end
    end
    assign hwif_out.CTRL.RESET.value = field_storage.CTRL.RESET.value;
    // Field: blob_detect_rle_regs.CTRL.START
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.START.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.START.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.CTRL.START.next = next_c;
        field_combo.CTRL.START.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.CTRL.START.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.START.load_next) begin
                field_storage.CTRL.START.value <= field_combo.CTRL.START.next;
            end
        end
    end
    assign hwif_out.CTRL.START.value = field_storage.CTRL.START.value;
    // Field: blob_detect_rle_regs.CTRL.IRQ_CLEAR
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.IRQ_CLEAR.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.IRQ_CLEAR.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.CTRL.IRQ_CLEAR.next = next_c;
        field_combo.CTRL.IRQ_CLEAR.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.CTRL.IRQ_CLEAR.value <= 1'h0;
        end else begin
            if(field_combo.CTRL.IRQ_CLEAR.load_next) begin
                field_storage.CTRL.IRQ_CLEAR.value <= field_combo.CTRL.IRQ_CLEAR.next;
            end
        end
    end
    assign hwif_out.CTRL.IRQ_CLEAR.value = field_storage.CTRL.IRQ_CLEAR.value;
    // Field: blob_detect_rle_regs.CTRL.BLOB_ADDR_AUTOINC
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.BLOB_ADDR_AUTOINC.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.BLOB_ADDR_AUTOINC.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.CTRL.BLOB_ADDR_AUTOINC.next = next_c;
        field_combo.CTRL.BLOB_ADDR_AUTOINC.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.CTRL.BLOB_ADDR_AUTOINC.value <= 1'h1;
        end else begin
            if(field_combo.CTRL.BLOB_ADDR_AUTOINC.load_next) begin
                field_storage.CTRL.BLOB_ADDR_AUTOINC.value <= field_combo.CTRL.BLOB_ADDR_AUTOINC.next;
            end
        end
    end
    assign hwif_out.CTRL.BLOB_ADDR_AUTOINC.value = field_storage.CTRL.BLOB_ADDR_AUTOINC.value;
    // Field: blob_detect_rle_regs.CTRL.THRESHOLD
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CTRL.THRESHOLD.value;
        load_next_c = '0;
        if(decoded_reg_strb.CTRL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CTRL.THRESHOLD.value & ~decoded_wr_biten[11:4]) | (decoded_wr_data[11:4] & decoded_wr_biten[11:4]);
            load_next_c = '1;
        end
        field_combo.CTRL.THRESHOLD.next = next_c;
        field_combo.CTRL.THRESHOLD.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.CTRL.THRESHOLD.value <= 8'h80;
        end else begin
            if(field_combo.CTRL.THRESHOLD.load_next) begin
                field_storage.CTRL.THRESHOLD.value <= field_combo.CTRL.THRESHOLD.next;
            end
        end
    end
    assign hwif_out.CTRL.THRESHOLD.value = field_storage.CTRL.THRESHOLD.value;
    // Field: blob_detect_rle_regs.HRES.HRES
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.HRES.HRES.value;
        load_next_c = '0;
        if(decoded_reg_strb.HRES && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.HRES.HRES.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.HRES.HRES.next = next_c;
        field_combo.HRES.HRES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.HRES.HRES.value <= 16'h500;
        end else begin
            if(field_combo.HRES.HRES.load_next) begin
                field_storage.HRES.HRES.value <= field_combo.HRES.HRES.next;
            end
        end
    end
    assign hwif_out.HRES.HRES.value = field_storage.HRES.HRES.value;
    // Field: blob_detect_rle_regs.VRES.VRES
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.VRES.VRES.value;
        load_next_c = '0;
        if(decoded_reg_strb.VRES && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.VRES.VRES.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.VRES.VRES.next = next_c;
        field_combo.VRES.VRES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.VRES.VRES.value <= 16'h320;
        end else begin
            if(field_combo.VRES.VRES.load_next) begin
                field_storage.VRES.VRES.value <= field_combo.VRES.VRES.next;
            end
        end
    end
    assign hwif_out.VRES.VRES.value = field_storage.VRES.VRES.value;
    // Field: blob_detect_rle_regs.BLOB_ADDR.BLOB_ADDR
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.BLOB_ADDR.BLOB_ADDR.value;
        load_next_c = '0;
        if(decoded_reg_strb.BLOB_ADDR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.BLOB_ADDR.BLOB_ADDR.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end else if(hwif_in.BLOB_ADDR.BLOB_ADDR.we) begin // HW Write - we
            next_c = hwif_in.BLOB_ADDR.BLOB_ADDR.next;
            load_next_c = '1;
        end
        field_combo.BLOB_ADDR.BLOB_ADDR.next = next_c;
        field_combo.BLOB_ADDR.BLOB_ADDR.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.BLOB_ADDR.BLOB_ADDR.value <= 8'h0;
        end else begin
            if(field_combo.BLOB_ADDR.BLOB_ADDR.load_next) begin
                field_storage.BLOB_ADDR.BLOB_ADDR.value <= field_combo.BLOB_ADDR.BLOB_ADDR.next;
            end
        end
    end
    assign hwif_out.BLOB_ADDR.BLOB_ADDR.value = field_storage.BLOB_ADDR.BLOB_ADDR.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [5:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 6'h0) begin
            readback_data_var[3] = field_storage.CTRL.BLOB_ADDR_AUTOINC.value;
            readback_data_var[11:4] = field_storage.CTRL.THRESHOLD.value;
        end
        if(rd_mux_addr == 6'h4) begin
            readback_data_var[0] = hwif_in.STATUS.READY.next;
            readback_data_var[1] = hwif_in.STATUS.FRAME_DONE.next;
            readback_data_var[2] = hwif_in.STATUS.OVERFLOW.next;
            readback_data_var[3] = hwif_in.STATUS.FRAME_DONE_IRQ.next;
            readback_data_var[11:4] = hwif_in.STATUS.BLOB_COUNT.next;
        end
        if(rd_mux_addr == 6'h8) begin
            readback_data_var[15:0] = field_storage.HRES.HRES.value;
        end
        if(rd_mux_addr == 6'hc) begin
            readback_data_var[15:0] = field_storage.VRES.VRES.value;
        end
        if(rd_mux_addr == 6'h10) begin
            readback_data_var[7:0] = field_storage.BLOB_ADDR.BLOB_ADDR.value;
        end
        if(rd_mux_addr == 6'h14) begin
            readback_data_var[31:0] = hwif_in.BLOB_COUNT_RD.BLOB_COUNT_RD.next;
        end
        if(rd_mux_addr == 6'h18) begin
            readback_data_var[31:0] = hwif_in.BLOB_SX.BLOB_SX.next;
        end
        if(rd_mux_addr == 6'h1c) begin
            readback_data_var[31:0] = hwif_in.BLOB_SY.BLOB_SY.next;
        end
        if(rd_mux_addr == 6'h20) begin
            readback_data_var[15:0] = hwif_in.BLOB_XMIN.BLOB_XMIN.next;
        end
        if(rd_mux_addr == 6'h24) begin
            readback_data_var[15:0] = hwif_in.BLOB_XMAX.BLOB_XMAX.next;
        end
        if(rd_mux_addr == 6'h28) begin
            readback_data_var[15:0] = hwif_in.BLOB_YMIN.BLOB_YMIN.next;
        end
        if(rd_mux_addr == 6'h2c) begin
            readback_data_var[15:0] = hwif_in.BLOB_YMAX.BLOB_YMAX.next;
        end
        if(rd_mux_addr == 6'h30) begin
            readback_data_var[31:0] = hwif_in.FRAME_CNT.FRAME_CNT.next;
        end
        if(rd_mux_addr == 6'h34) begin
            readback_data_var[15:0] = hwif_in.MAX_BLOBS_CFG.MAX_BLOBS_CFG.next;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
