`timescale 1ns/1ps
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package blob_detect_rle_regs_pkg;

    localparam BLOB_DETECT_RLE_REGS_DATA_WIDTH = 32;
    localparam BLOB_DETECT_RLE_REGS_MIN_ADDR_WIDTH = 6;
    localparam BLOB_DETECT_RLE_REGS_SIZE = 'h38;

    typedef struct {
        logic next;
    } blob_detect_rle_regs__status_reg__READY__in_t;

    typedef struct {
        logic next;
    } blob_detect_rle_regs__status_reg__FRAME_DONE__in_t;

    typedef struct {
        logic next;
    } blob_detect_rle_regs__status_reg__OVERFLOW__in_t;

    typedef struct {
        logic next;
    } blob_detect_rle_regs__status_reg__FRAME_DONE_IRQ__in_t;

    typedef struct {
        logic [7:0] next;
    } blob_detect_rle_regs__status_reg__BLOB_COUNT__in_t;

    typedef struct {
        blob_detect_rle_regs__status_reg__READY__in_t READY;
        blob_detect_rle_regs__status_reg__FRAME_DONE__in_t FRAME_DONE;
        blob_detect_rle_regs__status_reg__OVERFLOW__in_t OVERFLOW;
        blob_detect_rle_regs__status_reg__FRAME_DONE_IRQ__in_t FRAME_DONE_IRQ;
        blob_detect_rle_regs__status_reg__BLOB_COUNT__in_t BLOB_COUNT;
    } blob_detect_rle_regs__status_reg__in_t;

    typedef struct {
        logic [7:0] next;
        logic we;
    } blob_detect_rle_regs__blob_addr_reg__BLOB_ADDR__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_addr_reg__BLOB_ADDR__in_t BLOB_ADDR;
    } blob_detect_rle_regs__blob_addr_reg__in_t;

    typedef struct {
        logic [31:0] next;
    } blob_detect_rle_regs__blob_count_rd_reg__BLOB_COUNT_RD__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_count_rd_reg__BLOB_COUNT_RD__in_t BLOB_COUNT_RD;
    } blob_detect_rle_regs__blob_count_rd_reg__in_t;

    typedef struct {
        logic [31:0] next;
    } blob_detect_rle_regs__blob_sx_reg__BLOB_SX__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_sx_reg__BLOB_SX__in_t BLOB_SX;
    } blob_detect_rle_regs__blob_sx_reg__in_t;

    typedef struct {
        logic [31:0] next;
    } blob_detect_rle_regs__blob_sy_reg__BLOB_SY__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_sy_reg__BLOB_SY__in_t BLOB_SY;
    } blob_detect_rle_regs__blob_sy_reg__in_t;

    typedef struct {
        logic [15:0] next;
    } blob_detect_rle_regs__blob_xmin_reg__BLOB_XMIN__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_xmin_reg__BLOB_XMIN__in_t BLOB_XMIN;
    } blob_detect_rle_regs__blob_xmin_reg__in_t;

    typedef struct {
        logic [15:0] next;
    } blob_detect_rle_regs__blob_xmax_reg__BLOB_XMAX__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_xmax_reg__BLOB_XMAX__in_t BLOB_XMAX;
    } blob_detect_rle_regs__blob_xmax_reg__in_t;

    typedef struct {
        logic [15:0] next;
    } blob_detect_rle_regs__blob_ymin_reg__BLOB_YMIN__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_ymin_reg__BLOB_YMIN__in_t BLOB_YMIN;
    } blob_detect_rle_regs__blob_ymin_reg__in_t;

    typedef struct {
        logic [15:0] next;
    } blob_detect_rle_regs__blob_ymax_reg__BLOB_YMAX__in_t;

    typedef struct {
        blob_detect_rle_regs__blob_ymax_reg__BLOB_YMAX__in_t BLOB_YMAX;
    } blob_detect_rle_regs__blob_ymax_reg__in_t;

    typedef struct {
        logic [31:0] next;
    } blob_detect_rle_regs__frame_cnt_reg__FRAME_CNT__in_t;

    typedef struct {
        blob_detect_rle_regs__frame_cnt_reg__FRAME_CNT__in_t FRAME_CNT;
    } blob_detect_rle_regs__frame_cnt_reg__in_t;

    typedef struct {
        logic [15:0] next;
    } blob_detect_rle_regs__max_blobs_cfg_reg__MAX_BLOBS_CFG__in_t;

    typedef struct {
        blob_detect_rle_regs__max_blobs_cfg_reg__MAX_BLOBS_CFG__in_t MAX_BLOBS_CFG;
    } blob_detect_rle_regs__max_blobs_cfg_reg__in_t;

    typedef struct {
        blob_detect_rle_regs__status_reg__in_t STATUS;
        blob_detect_rle_regs__blob_addr_reg__in_t BLOB_ADDR;
        blob_detect_rle_regs__blob_count_rd_reg__in_t BLOB_COUNT_RD;
        blob_detect_rle_regs__blob_sx_reg__in_t BLOB_SX;
        blob_detect_rle_regs__blob_sy_reg__in_t BLOB_SY;
        blob_detect_rle_regs__blob_xmin_reg__in_t BLOB_XMIN;
        blob_detect_rle_regs__blob_xmax_reg__in_t BLOB_XMAX;
        blob_detect_rle_regs__blob_ymin_reg__in_t BLOB_YMIN;
        blob_detect_rle_regs__blob_ymax_reg__in_t BLOB_YMAX;
        blob_detect_rle_regs__frame_cnt_reg__in_t FRAME_CNT;
        blob_detect_rle_regs__max_blobs_cfg_reg__in_t MAX_BLOBS_CFG;
    } blob_detect_rle_regs__in_t;

    typedef struct {
        logic value;
    } blob_detect_rle_regs__ctrl_reg__RESET__out_t;

    typedef struct {
        logic value;
    } blob_detect_rle_regs__ctrl_reg__START__out_t;

    typedef struct {
        logic value;
    } blob_detect_rle_regs__ctrl_reg__IRQ_CLEAR__out_t;

    typedef struct {
        logic value;
    } blob_detect_rle_regs__ctrl_reg__BLOB_ADDR_AUTOINC__out_t;

    typedef struct {
        logic [7:0] value;
    } blob_detect_rle_regs__ctrl_reg__THRESHOLD__out_t;

    typedef struct {
        blob_detect_rle_regs__ctrl_reg__RESET__out_t RESET;
        blob_detect_rle_regs__ctrl_reg__START__out_t START;
        blob_detect_rle_regs__ctrl_reg__IRQ_CLEAR__out_t IRQ_CLEAR;
        blob_detect_rle_regs__ctrl_reg__BLOB_ADDR_AUTOINC__out_t BLOB_ADDR_AUTOINC;
        blob_detect_rle_regs__ctrl_reg__THRESHOLD__out_t THRESHOLD;
    } blob_detect_rle_regs__ctrl_reg__out_t;

    typedef struct {
        logic [15:0] value;
    } blob_detect_rle_regs__hres_reg__HRES__out_t;

    typedef struct {
        blob_detect_rle_regs__hres_reg__HRES__out_t HRES;
    } blob_detect_rle_regs__hres_reg__out_t;

    typedef struct {
        logic [15:0] value;
    } blob_detect_rle_regs__vres_reg__VRES__out_t;

    typedef struct {
        blob_detect_rle_regs__vres_reg__VRES__out_t VRES;
    } blob_detect_rle_regs__vres_reg__out_t;

    typedef struct {
        logic [7:0] value;
    } blob_detect_rle_regs__blob_addr_reg__BLOB_ADDR__out_t;

    typedef struct {
        blob_detect_rle_regs__blob_addr_reg__BLOB_ADDR__out_t BLOB_ADDR;
    } blob_detect_rle_regs__blob_addr_reg__out_t;

    typedef struct {
        blob_detect_rle_regs__ctrl_reg__out_t CTRL;
        blob_detect_rle_regs__hres_reg__out_t HRES;
        blob_detect_rle_regs__vres_reg__out_t VRES;
        blob_detect_rle_regs__blob_addr_reg__out_t BLOB_ADDR;
    } blob_detect_rle_regs__out_t;
endpackage
