// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef BLOB_DETECT_RLE_REGS_H
#define BLOB_DETECT_RLE_REGS_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - blob_detect_rle_regs::ctrl_reg
#define BLOB_DETECT_RLE_REGS__CTRL_REG__RESET_bm 0x1
#define BLOB_DETECT_RLE_REGS__CTRL_REG__RESET_bp 0
#define BLOB_DETECT_RLE_REGS__CTRL_REG__RESET_bw 1
#define BLOB_DETECT_RLE_REGS__CTRL_REG__RESET_reset 0x0
#define BLOB_DETECT_RLE_REGS__CTRL_REG__START_bm 0x2
#define BLOB_DETECT_RLE_REGS__CTRL_REG__START_bp 1
#define BLOB_DETECT_RLE_REGS__CTRL_REG__START_bw 1
#define BLOB_DETECT_RLE_REGS__CTRL_REG__START_reset 0x0
#define BLOB_DETECT_RLE_REGS__CTRL_REG__IRQ_CLEAR_bm 0x4
#define BLOB_DETECT_RLE_REGS__CTRL_REG__IRQ_CLEAR_bp 2
#define BLOB_DETECT_RLE_REGS__CTRL_REG__IRQ_CLEAR_bw 1
#define BLOB_DETECT_RLE_REGS__CTRL_REG__IRQ_CLEAR_reset 0x0
#define BLOB_DETECT_RLE_REGS__CTRL_REG__BLOB_ADDR_AUTOINC_bm 0x8
#define BLOB_DETECT_RLE_REGS__CTRL_REG__BLOB_ADDR_AUTOINC_bp 3
#define BLOB_DETECT_RLE_REGS__CTRL_REG__BLOB_ADDR_AUTOINC_bw 1
#define BLOB_DETECT_RLE_REGS__CTRL_REG__BLOB_ADDR_AUTOINC_reset 0x1
#define BLOB_DETECT_RLE_REGS__CTRL_REG__THRESHOLD_bm 0xff0
#define BLOB_DETECT_RLE_REGS__CTRL_REG__THRESHOLD_bp 4
#define BLOB_DETECT_RLE_REGS__CTRL_REG__THRESHOLD_bw 8
#define BLOB_DETECT_RLE_REGS__CTRL_REG__THRESHOLD_reset 0x80

// reg - blob_detect_rle_regs::status_reg
#define BLOB_DETECT_RLE_REGS__STATUS_REG__READY_bm 0x1
#define BLOB_DETECT_RLE_REGS__STATUS_REG__READY_bp 0
#define BLOB_DETECT_RLE_REGS__STATUS_REG__READY_bw 1
#define BLOB_DETECT_RLE_REGS__STATUS_REG__READY_reset 0x0
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_bm 0x2
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_bp 1
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_bw 1
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_reset 0x0
#define BLOB_DETECT_RLE_REGS__STATUS_REG__OVERFLOW_bm 0x4
#define BLOB_DETECT_RLE_REGS__STATUS_REG__OVERFLOW_bp 2
#define BLOB_DETECT_RLE_REGS__STATUS_REG__OVERFLOW_bw 1
#define BLOB_DETECT_RLE_REGS__STATUS_REG__OVERFLOW_reset 0x0
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_IRQ_bm 0x8
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_IRQ_bp 3
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_IRQ_bw 1
#define BLOB_DETECT_RLE_REGS__STATUS_REG__FRAME_DONE_IRQ_reset 0x0
#define BLOB_DETECT_RLE_REGS__STATUS_REG__BLOB_COUNT_bm 0xff0
#define BLOB_DETECT_RLE_REGS__STATUS_REG__BLOB_COUNT_bp 4
#define BLOB_DETECT_RLE_REGS__STATUS_REG__BLOB_COUNT_bw 8
#define BLOB_DETECT_RLE_REGS__STATUS_REG__BLOB_COUNT_reset 0x0

// reg - blob_detect_rle_regs::hres_reg
#define BLOB_DETECT_RLE_REGS__HRES_REG__HRES_bm 0xffff
#define BLOB_DETECT_RLE_REGS__HRES_REG__HRES_bp 0
#define BLOB_DETECT_RLE_REGS__HRES_REG__HRES_bw 16
#define BLOB_DETECT_RLE_REGS__HRES_REG__HRES_reset 0x500

// reg - blob_detect_rle_regs::vres_reg
#define BLOB_DETECT_RLE_REGS__VRES_REG__VRES_bm 0xffff
#define BLOB_DETECT_RLE_REGS__VRES_REG__VRES_bp 0
#define BLOB_DETECT_RLE_REGS__VRES_REG__VRES_bw 16
#define BLOB_DETECT_RLE_REGS__VRES_REG__VRES_reset 0x320

// reg - blob_detect_rle_regs::blob_addr_reg
#define BLOB_DETECT_RLE_REGS__BLOB_ADDR_REG__BLOB_ADDR_bm 0xff
#define BLOB_DETECT_RLE_REGS__BLOB_ADDR_REG__BLOB_ADDR_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_ADDR_REG__BLOB_ADDR_bw 8
#define BLOB_DETECT_RLE_REGS__BLOB_ADDR_REG__BLOB_ADDR_reset 0x0

// reg - blob_detect_rle_regs::blob_count_rd_reg
#define BLOB_DETECT_RLE_REGS__BLOB_COUNT_RD_REG__BLOB_COUNT_RD_bm 0xffffffff
#define BLOB_DETECT_RLE_REGS__BLOB_COUNT_RD_REG__BLOB_COUNT_RD_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_COUNT_RD_REG__BLOB_COUNT_RD_bw 32
#define BLOB_DETECT_RLE_REGS__BLOB_COUNT_RD_REG__BLOB_COUNT_RD_reset 0x0

// reg - blob_detect_rle_regs::blob_sx_reg
#define BLOB_DETECT_RLE_REGS__BLOB_SX_REG__BLOB_SX_bm 0xffffffff
#define BLOB_DETECT_RLE_REGS__BLOB_SX_REG__BLOB_SX_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_SX_REG__BLOB_SX_bw 32
#define BLOB_DETECT_RLE_REGS__BLOB_SX_REG__BLOB_SX_reset 0x0

// reg - blob_detect_rle_regs::blob_sy_reg
#define BLOB_DETECT_RLE_REGS__BLOB_SY_REG__BLOB_SY_bm 0xffffffff
#define BLOB_DETECT_RLE_REGS__BLOB_SY_REG__BLOB_SY_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_SY_REG__BLOB_SY_bw 32
#define BLOB_DETECT_RLE_REGS__BLOB_SY_REG__BLOB_SY_reset 0x0

// reg - blob_detect_rle_regs::blob_xmin_reg
#define BLOB_DETECT_RLE_REGS__BLOB_XMIN_REG__BLOB_XMIN_bm 0xffff
#define BLOB_DETECT_RLE_REGS__BLOB_XMIN_REG__BLOB_XMIN_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_XMIN_REG__BLOB_XMIN_bw 16
#define BLOB_DETECT_RLE_REGS__BLOB_XMIN_REG__BLOB_XMIN_reset 0x0

// reg - blob_detect_rle_regs::blob_xmax_reg
#define BLOB_DETECT_RLE_REGS__BLOB_XMAX_REG__BLOB_XMAX_bm 0xffff
#define BLOB_DETECT_RLE_REGS__BLOB_XMAX_REG__BLOB_XMAX_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_XMAX_REG__BLOB_XMAX_bw 16
#define BLOB_DETECT_RLE_REGS__BLOB_XMAX_REG__BLOB_XMAX_reset 0x0

// reg - blob_detect_rle_regs::blob_ymin_reg
#define BLOB_DETECT_RLE_REGS__BLOB_YMIN_REG__BLOB_YMIN_bm 0xffff
#define BLOB_DETECT_RLE_REGS__BLOB_YMIN_REG__BLOB_YMIN_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_YMIN_REG__BLOB_YMIN_bw 16
#define BLOB_DETECT_RLE_REGS__BLOB_YMIN_REG__BLOB_YMIN_reset 0x0

// reg - blob_detect_rle_regs::blob_ymax_reg
#define BLOB_DETECT_RLE_REGS__BLOB_YMAX_REG__BLOB_YMAX_bm 0xffff
#define BLOB_DETECT_RLE_REGS__BLOB_YMAX_REG__BLOB_YMAX_bp 0
#define BLOB_DETECT_RLE_REGS__BLOB_YMAX_REG__BLOB_YMAX_bw 16
#define BLOB_DETECT_RLE_REGS__BLOB_YMAX_REG__BLOB_YMAX_reset 0x0

// reg - blob_detect_rle_regs::frame_cnt_reg
#define BLOB_DETECT_RLE_REGS__FRAME_CNT_REG__FRAME_CNT_bm 0xffffffff
#define BLOB_DETECT_RLE_REGS__FRAME_CNT_REG__FRAME_CNT_bp 0
#define BLOB_DETECT_RLE_REGS__FRAME_CNT_REG__FRAME_CNT_bw 32
#define BLOB_DETECT_RLE_REGS__FRAME_CNT_REG__FRAME_CNT_reset 0x0

// reg - blob_detect_rle_regs::max_blobs_cfg_reg
#define BLOB_DETECT_RLE_REGS__MAX_BLOBS_CFG_REG__MAX_BLOBS_CFG_bm 0xffff
#define BLOB_DETECT_RLE_REGS__MAX_BLOBS_CFG_REG__MAX_BLOBS_CFG_bp 0
#define BLOB_DETECT_RLE_REGS__MAX_BLOBS_CFG_REG__MAX_BLOBS_CFG_bw 16
#define BLOB_DETECT_RLE_REGS__MAX_BLOBS_CFG_REG__MAX_BLOBS_CFG_reset 0x0

// addrmap - blob_detect_rle_regs
typedef struct __attribute__ ((__packed__)) {
    uint32_t CTRL;
    uint32_t STATUS;
    uint32_t HRES;
    uint32_t VRES;
    uint32_t BLOB_ADDR;
    uint32_t BLOB_COUNT_RD;
    uint32_t BLOB_SX;
    uint32_t BLOB_SY;
    uint32_t BLOB_XMIN;
    uint32_t BLOB_XMAX;
    uint32_t BLOB_YMIN;
    uint32_t BLOB_YMAX;
    uint32_t FRAME_CNT;
    uint32_t MAX_BLOBS_CFG;
} blob_detect_rle_regs_t;


static_assert(sizeof(blob_detect_rle_regs_t) == 0x38, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* BLOB_DETECT_RLE_REGS_H */
